static const unsigned char c64font[8*(256-64)] = {
#include "fonts/c64font.inc"
};

static const unsigned char p32font[32*256] = {
#include "fonts/8x32.inc"
};

static const unsigned char p19font[19*256] = {
#include "fonts/8x19.inc"
};

static const unsigned char p32wfont[32*256] = {
#include "fonts/16x32.inc"
};

static const unsigned char p8font[8*256] = {
#include "fonts/8x8.inc"
};

static const unsigned char p14font[14*256] = {
#include "fonts/8x14.inc"
};

static const unsigned char p16font[16*256] = {
#include "fonts/8x16.inc"
};
